[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.17"
dependencies = [
    "aiomysql>=0.2.0",
    "aiosqlite>=0.21.0",
    "fastapi[all]>=0.116.1",
    "greenlet>=3.2.3",
    "sqlalchemy>=2.0.41",
]
